#! /bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

xrb -merge $HOME/.Xresources

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

unfocused=#3A2F3F
focused=#C678DD

bspc config normal_border_color   $unfocused
bspc config active_border_color   $unfocused
bspc config focused_border_color  $focused
bspc config presel_feedback_color $select

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
